[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
solc = "0.8.20"
optimizer = true
optimizer_runs = 200

# Support multiple Solidity versions
solc_version = "0.8.20"
via_ir = false

# Additional solc versions for dependencies
[profile.default.solc_config]
"0.8.17" = { via_ir = false }
"0.8.20" = { via_ir = false }

remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@permit2/=lib/permit2/"
]

[rpc_endpoints]
localhost = "http://127.0.0.1:8545"
sepolia = "${SEPOLIA_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }

